#yml方式的配置文件
server:
  port: 8090
  context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot02?characterEncoding=utf-8&autoReconnect=true
    name: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
